/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductImport } from './routes/product'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as MineIndexImport } from './routes/mine/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as MineOrderImport } from './routes/mine/order'
import { Route as MineIntiveImport } from './routes/mine/intive'
import { Route as HomeShopImport } from './routes/home/shop'
import { Route as HomeCategoryImport } from './routes/home/category'

// Create/Update Routes

const ProductRoute = ProductImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MineIndexRoute = MineIndexImport.update({
  id: '/mine/',
  path: '/mine/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)

const MineOrderRoute = MineOrderImport.update({
  id: '/mine/order',
  path: '/mine/order',
  getParentRoute: () => rootRoute,
} as any)

const MineIntiveRoute = MineIntiveImport.update({
  id: '/mine/intive',
  path: '/mine/intive',
  getParentRoute: () => rootRoute,
} as any)

const HomeShopRoute = HomeShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => HomeRoute,
} as any)

const HomeCategoryRoute = HomeCategoryImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => HomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductImport
      parentRoute: typeof rootRoute
    }
    '/home/category': {
      id: '/home/category'
      path: '/category'
      fullPath: '/home/category'
      preLoaderRoute: typeof HomeCategoryImport
      parentRoute: typeof HomeImport
    }
    '/home/shop': {
      id: '/home/shop'
      path: '/shop'
      fullPath: '/home/shop'
      preLoaderRoute: typeof HomeShopImport
      parentRoute: typeof HomeImport
    }
    '/mine/intive': {
      id: '/mine/intive'
      path: '/mine/intive'
      fullPath: '/mine/intive'
      preLoaderRoute: typeof MineIntiveImport
      parentRoute: typeof rootRoute
    }
    '/mine/order': {
      id: '/mine/order'
      path: '/mine/order'
      fullPath: '/mine/order'
      preLoaderRoute: typeof MineOrderImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof HomeImport
    }
    '/mine/': {
      id: '/mine/'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface HomeRouteChildren {
  HomeCategoryRoute: typeof HomeCategoryRoute
  HomeShopRoute: typeof HomeShopRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeCategoryRoute: HomeCategoryRoute,
  HomeShopRoute: HomeShopRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/product': typeof ProductRoute
  '/home/category': typeof HomeCategoryRoute
  '/home/shop': typeof HomeShopRoute
  '/mine/intive': typeof MineIntiveRoute
  '/mine/order': typeof MineOrderRoute
  '/home/': typeof HomeIndexRoute
  '/mine': typeof MineIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product': typeof ProductRoute
  '/home/category': typeof HomeCategoryRoute
  '/home/shop': typeof HomeShopRoute
  '/mine/intive': typeof MineIntiveRoute
  '/mine/order': typeof MineOrderRoute
  '/home': typeof HomeIndexRoute
  '/mine': typeof MineIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/product': typeof ProductRoute
  '/home/category': typeof HomeCategoryRoute
  '/home/shop': typeof HomeShopRoute
  '/mine/intive': typeof MineIntiveRoute
  '/mine/order': typeof MineOrderRoute
  '/home/': typeof HomeIndexRoute
  '/mine/': typeof MineIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/product'
    | '/home/category'
    | '/home/shop'
    | '/mine/intive'
    | '/mine/order'
    | '/home/'
    | '/mine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product'
    | '/home/category'
    | '/home/shop'
    | '/mine/intive'
    | '/mine/order'
    | '/home'
    | '/mine'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/product'
    | '/home/category'
    | '/home/shop'
    | '/mine/intive'
    | '/mine/order'
    | '/home/'
    | '/mine/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  ProductRoute: typeof ProductRoute
  MineIntiveRoute: typeof MineIntiveRoute
  MineOrderRoute: typeof MineOrderRoute
  MineIndexRoute: typeof MineIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  ProductRoute: ProductRoute,
  MineIntiveRoute: MineIntiveRoute,
  MineOrderRoute: MineOrderRoute,
  MineIndexRoute: MineIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/product",
        "/mine/intive",
        "/mine/order",
        "/mine/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx",
      "children": [
        "/home/category",
        "/home/shop",
        "/home/"
      ]
    },
    "/product": {
      "filePath": "product.tsx"
    },
    "/home/category": {
      "filePath": "home/category.tsx",
      "parent": "/home"
    },
    "/home/shop": {
      "filePath": "home/shop.tsx",
      "parent": "/home"
    },
    "/mine/intive": {
      "filePath": "mine/intive.tsx"
    },
    "/mine/order": {
      "filePath": "mine/order.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx",
      "parent": "/home"
    },
    "/mine/": {
      "filePath": "mine/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
